name: login
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.12.9+3
  geocoder: ^0.2.1
  geolocator: ^5.3.2+2
  location: ^3.0.0
  
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0

  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter
  
  http: ^0.12.1
  shared_preferences: any

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/img/